### PR TITLE
Close instruments properly in tests

### PR DESCRIPTION
**Pull request by astafan8**
### Description

This PR tries to get rid of the following warnings in the CI tests run (tick box when the thing dissapears):
- [ ] Add info on how to close instruments in tests properly to "writing driver notebook" (somewhere else as well?)
- [x] .
```
--- Logging error ---
Traceback (most recent call last):
  File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 552, in close_all
    inst = cls.find_instrument(inststr)
  File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 649, in find_instrument
    raise KeyError('Instrument {} has been removed'.format(name))
KeyError: 'Instrument Joe has been removed'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/logging/__init__.py", line 1036, in emit
    stream.write(msg)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/capture.py", line 427, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 556, in close_all
    log.exception(f"Failed to close {inststr}, ignored")
Message: 'Failed to close Joe, ignored'
Arguments: ()
```
- [x] .
```
--- Logging error ---
Traceback (most recent call last):
  File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 552, in close_all
    inst = cls.find_instrument(inststr)
  File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 649, in find_instrument
    raise KeyError('Instrument {} has been removed'.format(name))
KeyError: 'Instrument inst has been removed'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/logging/__init__.py", line 1036, in emit
    stream.write(msg)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/capture.py", line 427, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 556, in close_all
    log.exception(f"Failed to close {inststr}, ignored")
Message: 'Failed to close inst, ignored'
Arguments: ()
```

- [x] .
```
--- Logging error ---
Traceback (most recent call last):
  File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 552, in close_all
    inst = cls.find_instrument(inststr)
  File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 649, in find_instrument
    raise KeyError('Instrument {} has been removed'.format(name))
KeyError: 'Instrument s46_bad_state has been removed'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/logging/__init__.py", line 1036, in emit
    stream.write(msg)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/capture.py", line 427, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 556, in close_all
    log.exception(f"Failed to close {inststr}, ignored")
Message: 'Failed to close s46_bad_state, ignored'
Arguments: ()
```

### Reasoning:

The thing is that the instrument instance will be created and will be
added to the registry of instrument instances thanks to the code of the
parent class of the 'S46'. However, in this test the __init__ of 'S46'
will break by intention which means that the instrument instance will
not be returned to the test (an exception will be raised) but that
instrument instance will still remain in the global registry of the
instrument instances which will cause a warning at the end of the test
execution. So, the way to remove that "almost created instance" of the
instrument is to use "close_all" class method (on the 'S46' instrument
class in order to be more specific with what needs to be closed).

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Have not done a full review but this sounds reasonable. It would be great if partially created instruments were never added to the instrument registry in general but that can wait to another pr

**Comment by astafan8** [comment]
> t would be great if partially created instruments were never added to the instrument registry in general

indeed. some time ago i wanted to look into it but found that but it's not a 5 minute fix.... so, yeah, other PR in some bright future

**Comment by astafan8** [comment]
@jenshnielsen thanks for prompt merging but I was in the process of adding a note to the notebook :) but it's ok, i'll open a new PR for that shortly

**Comment by astafan8** [comment]
@jenshnielsen i decided not to add a note becuase I think i found at least a hacky way to get around this, i'll submit a pr shortly

**Comment by jenshnielsen** [comment]
Ok great

**Comment by astafan8** [comment]
@jenshnielsen my humble research seems to show that we have been experiencing something like https://github.com/pytest-dev/pytest/issues/5502 or https://github.com/pytest-dev/pytest/issues/3828 . which comes from the fact that `Instrument.close_all` (that is executed at "exit", `atexit`) in case on an exception logs the exception with module level `log` instance. the exception happens becuase the useless instance of the instrument is still in the registry hence `Instrument.find_instrument` raises. So, "sometimes" when running pytest, that `log` instance`  can't log the exception because as per the issues mentioned above `pytest` could be doing some stream/logging hijacking stuff. So, what we can is to wait for `pytest` to fix things, for sure. But, in order to not have these `Instrument.find_instrument` calls raining an exception when called from  `Instrument.close_all`, we could consider finally using the right tools for the job - use [weakref.WeakValueDictionary](https://docs.python.org/3.7/library/weakref.html#weakref.WeakValueDictionary) for `_all_instruments` which will automatically take care of the case where a weakref is "dead". What do you think?

**Comment by jenshnielsen** [comment]
That sounds reasonable at a first glance. Can you create an issue for improvements to `_all_instruments` somewhere with this info so that this is not lost.

**Pull request merged**
