### PR TITLE
Remove outdated documents: Tutorial

### PR DESCRIPTION
**Pull request by GateBuilder**
This PR proposes to remove

- http://qcodes.github.io/Qcodes/user/tutorial.html

due to 

1. The content is outdated.
2. The content that is relevant to legacy code does already exists in:

- http://qcodes.github.io/Qcodes/examples/legacy/Tutorial.html
- http://qcodes.github.io/Qcodes/examples/legacy/Combined%20Parameters.html

I have checked if there are any pointers to this file to ensure there are no broken links. I could not locate anything. 

@jenshnielsen

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Thanks. I think you need to remove the tutorial from the index.rst file in the same folder

**Comment by WilliamHPNielsen** [comment]
There is a link in this file: https://github.com/QCoDeS/Qcodes/blob/master/docs/user/index.rst

**Comment by jenshnielsen** [comment]
The driver link in the intro.rst file also refers to this document. I suggest building docs locally when making changes before pushing. This will significantly reduce the feedback loop

**Comment by jenshnielsen** [comment]
It's probably because you need to do a make clean before building when you have removed a file. Otherwise it will be in the cache

**Pull request merged**
