### PR TITLE
[wip] [discussion] Dev/move deps to interdependencies

### PR DESCRIPTION
**Pull request by WilliamHPNielsen**
This PR may replace #1438 

The idea is to move all information about how parameters are related to each other into a new `InterDependencies` object and thus out of the the `ParamSpec`.

Changes proposed in this pull request:
- Make `ParamSpec` only have four attributes: name, datatype, label, unit
- Make `InterDependencies` take three input arguments: dependencies, inferences, and standalones
- Make the type of those arguments do most of the validation (nice, huh?)

All validation takes place upon instantiating an `InterDependencies` object, i.e. if it exists, it is valid.

You can get an impression of how this will work by looking at the `ParamSpecBase` and the `InterDependencies_` objects of this PR. If you like it, we can begin to discuss how to proceed with rolling this out, deprecating old things etc. I have a plan for that, but let's first decide whether we like this design.

Open questions:

- [ ] How should the new `InterDependencies` object serialize itself? Do we need a DB upgrade?
- [ ] Are the rules imposed by `InterDependencies_` for how parameters may relate to each other the correct rules. I _think_ they are, but I'd like your input on that.

@QCoDeS/core 

AB#2861

### CODE REVIEW

**Comment by WilliamHPNielsen** [comment]
Just to flesh it out a bit, you would use it like this:

```python

ps1 = ParamSpec(name='dac_ch1_cv', paramtype='numerical', label='Gate Voltage', unit='V')
ps2 =  ParamSpec(name='dac_ch2_cv', paramtype='numerical', label='Plunger Voltage', unit='V')
ps3 = ParamSpec(name='lockin1_g', paramtype='numerical', label='conductance', unit='e^2/h')

idps = InterDependencies(dependencies={ps3: (ps1, ps2)}
```

**Comment by Dominik-Vogel** [comment]
As we discussed over lunch the other day, I really like the idea. This way we can keep the `ParamSpec` and the `Interdependencies` both imutable.
Serialization is a good question.
Relevant for that may be:
How will Paramspecs be used? Shall we ask/get users to always recycle when possible?
Maybe we need a ParamSpecID

**Comment by WilliamHPNielsen** [comment]
AB#2861

**Comment by WilliamHPNielsen** [comment]
Closed in favour of #1477 using the cool new draft PR feature

**Pull request closed without merging**
