### PR TITLE
Mercury fixes

### PR DESCRIPTION
**Pull request by jenshnielsen**
Some small issues found while working with the code on T10

@MerlinSmiles @QCoDeS/core

### CODE REVIEW

**Comment by MerlinSmiles** [comment]
@jenshnielsen are you sure that your changes of `[self.axes.index(ax)]` to `[0]` actually work?
the `_ATOB` makes setpoint and field a `len(ax)` array, no?

**Comment by MerlinSmiles** [comment]
while youre at it, maybe we want to change this function:
```
    def _carttosphere(self, field):
        field = np.array(field)
        r = np.sqrt(np.sum(field**2))
        if r == 0:
            theta = 0
            phi = 0
        else:
            theta = np.arccos(field[2] / r)
            phi = np.arctan2(field[1],  field[0])
            if phi<0:
                phi = phi+np.pi*2
        return [r, theta, phi]
```
basically adding:
```
            if phi<0:
                phi = phi+np.pi*2
```
to make sure phi is always positive?

**Comment by MerlinSmiles** [comment]
and maybe we want to define if we run the magnet in current or field mode, and then remove all the `...C` guys

**Comment by jenshnielsen** [comment]
@MerlinSmiles you are probably right but unfortunately it doesn't take that code path for other parameters such as z field

**Comment by MerlinSmiles** [comment]
now I see the issue, yes its only going there for the 'current' version of sending the field. Stupid mistake.

A note on the side, using the current parameters instead of tesla parameters gives you one decimal place higher in resolution on the magnet.

**Comment by jenshnielsen** [comment]
Agreed with @MerlinSmiles in Slack

**Pull request merged**
