### PR TITLE
updates to IVVI driver

### PR DESCRIPTION
**Pull request by eendebakpt**
- better variable name
- add term character setting;
- replace version function with dummy

@giulioungaretti

### CODE REVIEW

**Comment by AdriaanRol** [comment]
@eendebakpt , Would it make sense to make a child class (in the same file), that does this overwriting of the get version command. Then we can still use it (we use it as a check to see if we are connected).

**Comment by giulioungaretti** [comment]
This looks good to me, but @AdriaanRol and @eendebakpt  you have to agree on the version function! :P

**Comment by eendebakpt** [comment]
@AdriaanRol @giulioungaretti A child class indeed seems like a good idea, or an option in the IVVI constructor. I will make something for it. Note: for the default I will implement the dummy command, as the command really mess up the connection module.

**Comment by AdriaanRol** [comment]
@eendebakpt , I think that dummy indeed makes sense as a default, given how it messes up things. Looking forward to your input.

**Comment by giulioungaretti** [comment]
great! Thanks for the contribution once again!

**Comment by eendebakpt** [comment]
@AdriaanRol @giulioungaretti Here it is.

**Comment by giulioungaretti** [comment]
LGTM!

**Comment by AdriaanRol** [comment]
Let's 💃

**Pull request merged**
