### PR TITLE
feat: Add basic driver for Keysight N6705B

### PR DESCRIPTION
**Pull request by neildick**
This is a bare bones driver for the Keysight N6705B DC power
supply.

Changes proposed in this pull request:
- Add basic driver for this power supply 

@astafan8 

Hey guys, could you have a quick look over this please. I had a quick look around but couldn't find a driver for this power supply.  I mostly copied the driver for the B296A. The programming manual is [here](http://literature.cdn.keysight.com/litweb/pdf/N6705-90902.pdf)

### CODE REVIEW

**Comment by WilliamHPNielsen** [comment]
I think it looks good. You could consider:

- Using f-strings instead of `.format`
- Adding a test with PyVISA-sim

But I'm not gonna press hard for either.

**Comment by neildick** [comment]
Hey @WilliamHPNielsen :) 
Done and done. 
This is my first time working with PyVisa-sim so maybe just double check I didn't do anything silly

**Comment by WilliamHPNielsen** [comment]
@neildick, not bad for a first timer ;)
It looks good, thank you!

**Comment by neildick** [comment]
I can copy & paste with the best of them mate ;) Thanks for that!

**Pull request merged**
