### PR TITLE
make register_parameter match add_result for array_parameter

### PR DESCRIPTION
**Pull request by jenshnielsen**
@WilliamHPNielsen Fixes an inconsistency between add_parameter and the register_parameter for ArrayParameters. At the one uses the name of the root instrument but the other users the full name. This fails for an arrayparameter inside a channel since one name will contain the name of the channel but the other one does not.

### CODE REVIEW

**Comment by neildick** [comment]
👍 Cherry-picking this into master fixes the issue on my end.

**Comment by astafan8** [comment]
do we have a test that covers this bug?

**Comment by jenshnielsen** [comment]
@astafan8 Obviously not :( the coverage remains the same and no test failures

**Comment by jenshnielsen** [comment]
@astafan8 This now has a test. Assuming Appveyor passes this should be ready for review

**Pull request merged**
