### PR TITLE
Fix/infiniium

### PR DESCRIPTION
**Pull request by sohailc**
This PR fixes the Infiniium oscilloscope driver by Agilent. In particular, the issue that an exception is raised when xorigin and xincrem parameters change to much between preparing curvedata and actual acquisition. What we want to do instead is interpolate between the actual sampling points such that we get the data at the requested sampling points.

@Dominik-Vogel I believe you were the original author of this driver, so I am including you as a reviewer.

### CODE REVIEW

**Comment by sohailc** [comment]
@Dominik-Vogel Can you have a look, please?

**Comment by WilliamHPNielsen** [comment]
@sohailc I'm glad we agree about the interpolation. Regarding the time frame for #1263, it may indeed be the best thing to do the workaround that you suggest. Not much will happen this year at least. 

But just for my understanding, since I haven't used the scope, can you perhaps elaborate on how often this exception is thrown? And is there no known way to prevent it? "Hit or miss" does sound very bad.

**Comment by sohailc** [comment]
How often an exception is thrown depends on you settings (e.g. the length of the trace) and how long the time period is between preparing for the acquisition and performing the acquisition. But even under the best of circumstances, for me it failed ~20-30% of the time.

**Comment by WilliamHPNielsen** [comment]
Okay, that's bad indeed.

**Pull request closed without merging**
