### PR TITLE
Loop dataset: do not use hardcoded value to look for default parameter name

### PR DESCRIPTION
**Pull request by peendebak**
Changes proposed in this pull request:
- Update `default_parameter_name` to not use a hardcoded value for searching. This causus problems for datasets where we have a dependent variable called `qubit_fractions` and a dependent variable such as `amplitude_variation`.

### CODE REVIEW

**Review by astafan8 — COMMENTED** [review]
@peendebak question out of curiosity - would this be an option to use the ``metadata['default_parameter_name']`` to overrule the default `'amplitude'`?

**Comment by peendebak** [comment]
> @peendebak question out of curiosity - would this be an option to use the `metadata['default_parameter_name']` to overrule the default `'amplitude'`?

That is possible, but a lot of work. Setting the `default_parameter_name` in our scan functions is possible, but these datasets get passed, modified, sliced, averaged, etc. in post-processing and most of the time the `metadata` is not fully copied. With hindsight, setting the default value to some value is a mistake I believe.

**Comment by peendebak** [comment]
> @peendebak thanks for explaining. then since it's a breaking change, could you add a note about it to the changelog of the next release (we ask PR authors to do that for breaking changes so that the person who's going to do a release does not have to remember to check for that)?

@astafan8 Where should I add the changelog entry?

**Comment by astafan8** [comment]
> Where should I add the changelog entry?

create a docs/changes/0.27.0.rst file, and add it there (and also mention this new rst file in the docs/changes/index.rst . (see and example here https://github.com/QCoDeS/Qcodes/pull/3089 )

**Comment by eendebakpt** [comment]
@astafan8 I added a changelog

**Review by astafan8 — APPROVED** [review]

**Pull request merged**
