### PR TITLE
fix for slack module when a user has not send any messages

### PR DESCRIPTION
**Pull request by peendebak**
The slack module generates an error when retreiving the latest timestamp if a user has not posted any messages. This PR assigns a None value in that case.

@astafan8

### CODE REVIEW

**Comment by peendebak** [comment]
@astafan8 There is an error from codacy 'Import outside toplevel (qcodes.utils.slack)' that I do not know how to resolve. The import needs to be inside the patch environment

**Comment by jenshnielsen** [comment]
@peendebak Codacy is a linting tool and marked as not required so feel free to ignore it when it does not make sense to make the change

**Comment by jenshnielsen** [comment]
@peendebak could you either merge master into this branch or give admins rights to commit to the branch so that I can do it

**Comment by peendebak** [comment]
> @peendebak could you either merge master into this branch or give admins rights to commit to the branch so that I can do it

@jenshnielsen Done

**Pull request merged**
