### PR TITLE
Add locking to IVVI driver

### PR DESCRIPTION
**Pull request by peendebak**
Changes proposed in this pull request:
- Add locks to the IVVI driver

The locking is optional, so without enabling them the behaviour of the driver is unchanged. The locks are needed for safety of our systems (otherwise we could have set random values to the DACs).

@giulioungaretti @AdriaanRol @WilliamHPNielsen @jenshnielsen

### CODE REVIEW

**Comment by giulioungaretti** [comment]
@eendebakpt looks good to me! @AdriaanRol  ?

**Comment by AdriaanRol** [comment]
@eendebakpt I'm a bit confused as to what the lock actually does. I guess it relates to multi threading in some way but I'm not really sure. Could you add a docstring explaining or referencing the appropriate concept? 

and @giulioungaretti , I'm also curious how the merge of this relates to the merge of #541 , which contains some related fixes to the IVVI driver and is also good to merge from what I can tell.

**Comment by peendebak** [comment]
@AdriaanRol @giulioungaretti The IVVI driver is not thread safe. We use threads in our code in several ways: 1) a parameterviewer gui that runs in the background 2) the variable explorer of our IDE uses threads to display variables 3) some of our measurement functions use threads. Without the locking mechanism our IVVI driver will lock up during measurements.

**Comment by AdriaanRol** [comment]
OK, that explains why we don't experience that. 

Thanks for the comment. @giulioungaretti lgtm let's 💃

**Pull request merged**
