### PR TITLE
Feature: Instruments snapshot exclude parameters

### PR DESCRIPTION
**Pull request by nyxus**
Changes proposed in this pull request:
- Added way to exclude parameters from the instruments snapshot
- Added another test case to the param_to_skip_update of the instruments snapshot test

At the DiCarlo lab, we use a couple of devices which have many (instruments) parameters (E.g., QWG, HDAWG8, UHFQC). Most of these parameters are not useful for us to log (or backup) via the snapshot feature. There are so many useless parameters that we have problems with backing up all the information. With this feature, the user or device manufacture can specify which parameters not to include.

This code is tested on our devices, and I added tests to the snapshot tests.   

@WilliamHPNielsen, @AdriaanRol

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Thanks. Is there a particular reason why the snapshot_value and snapshot_get options on the individual parameters does not enable you to do what you want? I.e the two bools documented here https://qcodes.github.io/Qcodes/api/parameters/parameter.html#qcodes.instrument.parameter.Parameter

**Comment by nyxus** [comment]
@jenshnielsen, both the `snapshot_get` and `snapshot_value` still leave the parameter in the output of the snapshot. They change the behaviour of the parameter when the snapshot is called. 
For example, the QWG (inhouse developed AWG) has parameters to assign waves to codewords on a channel (`codeword_1_ch1_waveform('sine')`). The QWG has 4 channels and per-channel 1024 codewords. In total, this adds 4096 parameters (or entries) to the snapshot. The same problems occur for the HDAWG8 which has 8 channels and even more codewords than the QWG. We do not need these parameters in the snapshot because the information is logged (also) on a different level. Therefore the `params_to_exclude` which will completely leave out these kinds of parameters from the snapshot.

**Comment by nyxus** [comment]
I'm looking at the errors of the CI, and I do not know why they fail. 
Error 1:
```
qcodes/instrument_drivers/ZI/ZIUHFLI.py:1655:5: error: Signature of "snapshot_base" incompatible with supertype "InstrumentBase"
qcodes/instrument_drivers/ZI/ZIHDAWG8.py:66:5: error: Signature of "snapshot_base" incompatible with supertype "InstrumentBase"
```
I added a new optional parameter, why does it fail? 

Error 2:
The Travis errors are also a bit weird. But looking at other builds the also fail with the same errors. So I guess this has nothing to do with this PR?

**Comment by jenshnielsen** [comment]
@nyxus thanks for the explanation that makes sense. One could also consider extending the parameter to fully have this feature. I am honestly not sure what is the cleanest.

 As a historic context. The parameter_to_skip update functionality is mainly there so that we can handle instruments that have a shortcut functionality allowing the update to be done as a one shot operation for all parameters. 

The 2 drivers overwrites the snapshot_base method. I think they just need to be updated too so that the signature of the method is kept in sync.

**Comment by nyxus** [comment]
After some internal discussion in DCL we decided to also implement this feature as suggested by @jenshnielsen. In this way clear that a property of a parameter instead of a separate list. It also continues the idea of the behaviour of the snapshot to include in the parameter itself (see `snapshot_get` and `snapshot_value`). See PR #1653 for the new implementation.

**Comment by WilliamHPNielsen** [comment]
Closing this in favour of #1653

**Pull request closed without merging**
