### PR TITLE
AMI430 remove has_current_rating that does not work with new firmware versions

### PR DESCRIPTION
**Pull request by jenshnielsen**

### CODE REVIEW

**Review by astafan8 — APPROVED** [review]
and the "new firmware versions" are 2.62 and the 3.xx?

**Comment by jenshnielsen** [comment]
It is newer than some version older than 2.62 but I am not sure which version. @FarBo will verify

**Comment by FarBo** [comment]
@jenshnielsen 

I set has_current_rating: true in the station file of a magnet running 2.62. This set caused snapshot warning for current_rating and field_rating in the load time of the instrument. To make sure that these two parameters are not present for this firmware, I called them, which returned me error. All means that the changes in this PR is correct.

**Comment by jenshnielsen** [comment]
@FarBo thanks for confirming. @astafan8 Do you agree this is the correct solution then ?

**Review by astafan8 — APPROVED** [review]
I agree! thanks @FarBo and @jenshnielsen !

**Pull request merged**
