### PR TITLE
Add Setpoint units

### PR DESCRIPTION
**Pull request by jenshnielsen**
Fixes part of #498 by adding a setpoint units which .are propagated to units for the setpoint data arrays

Done on top of #500 so that should be merged first

Needs some testing I think

### CODE REVIEW

**Comment by giulioungaretti** [comment]
Good idea with testing!

**Comment by giulioungaretti** [comment]
The underlying bits are so spaghetti that having a test will just make it a lot easier to understand what's going on 🗡

**Comment by jenshnielsen** [comment]
Yes especially `_parameter_arrays` is more complicated that it needs to be.

**Comment by jenshnielsen** [comment]
Should remember to add this to meta_attrs

**Pull request closed without merging**
