### PR TITLE
Fix/current voltage parameter

### PR DESCRIPTION
**Pull request by jenshnielsen**
These parameters were missed in the original conversion

Also needed to change the SR560 driver default values to actually make it work

### CODE REVIEW

**Comment by MerlinSmiles** [comment]
@jenshnielsen could you instead of changing the default value, add 'DC' to the cutoffs? That was my mistake, the instrument can actually turn off the filter and that is called DC on the instrument.

**Comment by jenshnielsen** [comment]
Ok thanks for the update @MerlinSmiles

**Comment by jenshnielsen** [comment]
@MerlinSmiles done

**Comment by giulioungaretti** [comment]
LGTM

**Pull request merged**
