### PR TITLE
add handling of unknown types to JSON stream

### PR DESCRIPTION
**Pull request by peendebak**
@alexcjohnson @giulioungaretti

### CODE REVIEW

**Comment by peendebak** [comment]
@alexcjohnson Added the fix as suggested.

**Comment by alexcjohnson** [comment]
Removing the `finally` was part of the suggested change (and the most important part, as it could lead to confusing errors). The other part is handling the two branches symmetrically. Right now `try` returns, but `except` sets `s`, which gets returned in the outer scope. Not a huge deal (so 💃 ), but really they should either both return or both set `s` for a later return.

Incidentally, we don't seem to have any tests for `NumpyJSONEncoder` do we? It's probably largely covered by way of metadata tests, but if you wanted to write a short test for it in `test_helpers.py` you would have my undying gratitude 🍻

**Comment by peendebak** [comment]
@alexcjohnson @giulioungaretti Added a basic test

**Comment by peendebak** [comment]
@giulioungaretti  @alexcjohnson  Even tough the :dancer: is there, I cannot merge myself any more

**Comment by giulioungaretti** [comment]
@eendebakpt thanks for the PR, will prettyify the tests and merge!

**Pull request closed without merging**
