### PR TITLE
Hypothesis timings

### PR DESCRIPTION
**Pull request by jenshnielsen**
@WilliamHPNielsen Seems like 1000 ms is not always enough on travis so increase it here.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
It failed here https://travis-ci.org/QCoDeS/Qcodes/jobs/314756807 on master

**Comment by jenshnielsen** [comment]
Travis is really slow for some reason. The test is apparently 10 times slower on Travis than when I run it locally

**Comment by WilliamHPNielsen** [comment]
Should we just disable deadlines for that test then?

**Comment by jenshnielsen** [comment]
Maybe. Now another one was slow. I am a bit worried that something funny is going on but perhaps its just sharing the travis service with other users

**Pull request merged**
