### PR TITLE
fix: Respond to issue #546

### LINKED ISSUE #546: bug: decadac getting and setting voltages fails unpredictably
### Steps to reproduce
1. start Harvard Decadac and  import a qcodes instrument instrument:

```
from qcodes.instrument_drivers.Harvard.Decadac import Decadac
sl0 = Decadac('dec_slot_0', port=5, slot=0)
```

2. run 

`sl0.ch1_voltage(0)`

3. fail as below, seems like its something to do with the mode (which is set in the init but somehow that isn't reliable), It is also not super reliable to fix by setting the mode to 1 but seems to work if I set it to 0 and back to 1 a few times...

### Expected behaviour
should set the voltage

### Actual behaviour
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-e543db036233> in <module>()
----> 1 sl0.ch1_voltage(0)

a:\qcodes\qcodes\instrument\parameter.py in __call__(self, *args)
    133         else:
    134             if self.has_set:
--> 135                 self.set(*args)
    136             else:
    137                 raise NotImplementedError('no set cmd found in' +

a:\qcodes\qcodes\instrument\parameter.py in _validate_and_sweep(self, value)
    945             e.args = e.args + (
    946                 'setting {} to {}'.format(self.full_name, repr(value)),)
--> 947             raise e
    948 
    949     def set_step(self, step, max_val_age=None):

a:\qcodes\qcodes\instrument\parameter.py in _validate_and_sweep(self, value)
    929             step_clock = time.perf_counter()
    930 
--> 931             for step_val in self._sweep_steps(value):
    932                 self._set(step_val)
    933                 self._save_val(step_val)

a:\qcodes\qcodes\instrument\parameter.py in _sweep_steps(self, value)
    891         state = self._latest()
    892         if state['ts'] is None or state['ts'] < oldest_ok_val:
--> 893             start_value = self.get()
    894         else:
    895             start_value = state['value']

a:\qcodes\qcodes\instrument\parameter.py in get(self)
    826         except Exception as e:
    827             e.args = e.args + ('getting {}'.format(self.full_name),)
--> 828             raise e
    829 
    830     def _valmapping_get_parser(self, val):

a:\qcodes\qcodes\instrument\parameter.py in get(self)
    821     def get(self):
    822         try:
--> 823             value = self._get()
    824             self._save_val(value)
    825             return value

a:\qcodes\qcodes\utils\command.py in __call__(self, *args)
    175             raise TypeError(
    176                 'command takes exactly {} args'.format(self.arg_count))
--> 177         return self.exec_function(*args)

a:\qcodes\qcodes\instrument_drivers\Harvard\Decadac.py in _getvoltage(self, channel)
    129         response = temp[::-1]
    130 
--> 131         rawvoltage = self._code2voltage(response, channel)
    132         actualvoltage = rawvoltage - self._offsets[channel]
    133 

a:\qcodes\qcodes\instrument_drivers\Harvard\Decadac.py in _code2voltage(self, code, channel)
    232         """
    233 
--> 234         code = float(code)
    235         translationdict = {1: lambda x: (x+1)*20/2**16-10,
    236                            2: lambda x: (x+1)*10/2**16,

ValueError: ("could not convert string to float: '0! M 0'", 'getting dec_slot_0_ch1_voltage', 'setting dec_slot_0_ch1_voltage to 0')
```

@WilliamHPNielsen @giulioungaretti

### PR DESCRIPTION
**Pull request by WilliamHPNielsen**
Unfortunately not tested.

Should fix #546

@jenshnielsen @nataliejpg @MerlinSmiles

### CODE REVIEW

**Comment by MerlinSmiles** [comment]
@WilliamHPNielsen I dont think your mode 1 will work, you need to send fine channel data if you want to use it.
I suggest to either remove mode 1, or handle the fine channel stuff.
https://github.com/qdev-dk/matlab-qd/blob/master/%2Bqd/%2Bins/HRDecaDACChannel.m

**Comment by WilliamHPNielsen** [comment]
@MerlinSmiles That is a good point. I removed the fine mode.

**Comment by nataliejpg** [comment]
Looks good. Haven't tested but can next time I'm measuring. Considering that (thanks to @MerlinSmiles) I made almost identical changes locally i can't see it not working.

**Comment by giulioungaretti** [comment]
@nataliejpg @WilliamHPNielsen @MerlinSmiles  merge ?

**Comment by nataliejpg** [comment]
I think so. Seems like when it's ready to merge #568 will replace most of this driver though.

**Comment by MerlinSmiles** [comment]
LGTM but cant test

**Comment by giulioungaretti** [comment]
@WilliamHPNielsen will merge and see if we get more errors.

**Pull request merged**
