### PR TITLE
feat: Add driver for Rohde & Schwarz SMF100A Signal Generator

### PR DESCRIPTION
**Pull request by rohit19081995**
Add driver for Rohde & Schwarz SMF100A Signal Generator

Fixes Nothing.

Changes proposed in this pull request:
- Add driver for Rohde & Schwarz SMF100A Signal Generator

@ThorvaldLarsen

### CODE REVIEW

**Comment by WilliamHPNielsen** [comment]
Hi @rohit19081995! Thanks for contributing to QCoDeS. This PR is already pretty high quality, but there are a few minor issues that need to be fixed before we can merge it. I'll request those changes in a minute.

**Comment by WilliamHPNielsen** [comment]
@rohit19081995, also, if you're up for it, I'd be nice if you could add a small test of the driver using PyVISA-sim. You can see an example of how to do it here: https://github.com/QCoDeS/Qcodes/blob/master/docs/examples/Creating%20Simulated%20PyVISA%20Instruments.ipynb

**Comment by rohit19081995** [comment]
@WilliamHPNielsen Thanks for the feedback. This is my first PR ever. I made the changes to the driver and pushed it to the branch in my fork. I will write the test soon. I will most probably be adding more drivers soon.

**Comment by WilliamHPNielsen** [comment]
@rohit19081995, that sounds

- good
- awesome

Let me know if you need any help with the test writing, pyvisa-sim can be a bit recalcitrant at times.

**Comment by astafan8** [comment]
@rohit19081995 

The driver in this pull request will not be supported by QCoDeS developers, and, hence, is a **community driver**. Please close this pull-request and open a new one against [`qcodes_contrib_drivers`](https://github.com/QCoDeS/Qcodes_contrib_drivers) repository. QCoDeS developers will close this pull-request unconditionally **in 2 weeks**.

[Read about `qcodes_contrib_drivers` repository and python package here.](https://github.com/QCoDeS/Qcodes_contrib_drivers#qcodes-contrib-drivers)

**Comment by astafan8** [comment]
@rohit19081995 

I'm closing this PR. Feel free to open this against [Qcodes_contrib_drivers](https://github.com/QCoDeS/Qcodes_contrib_drivers).

**Pull request closed without merging**
