### PR TITLE
Add CW mode to PNA N52xx

### PR DESCRIPTION
**Pull request by cjchua**
Changes proposed in this pull request:

Adds CW mode to PNA 52xx
Adds a driver for the PNA N5222B

### CODE REVIEW

**Review by astafan8 — APPROVED** [review]
Thank you! And congratulations with the first contribution to qcodes @cjchua :)

**Comment by astafan8** [comment]
bors merge

**Comment by astafan8** [comment]
@cjchua could you add a newsfragment file so that this change gets mentioned in the changelog? similar to how it's done here https://github.com/QCoDeS/Qcodes/pull/3688

**Comment by astafan8** [comment]
bors merge

**Comment by jenshnielsen** [comment]
bors merge

**Pull request merged**
