### PR TITLE
Allow tuple selection for ChannelLists

### PR DESCRIPTION
**Pull request by ThorvaldLarsen**
We are currently calling channellists for measurements with alazar and VNA. Sometimes one wants to take data from only a subset of the channels in the channellists however currently one can only choose slices or a single channel.
This PR allows one to take data from a subset of a channellist defined by a tuple (e.g. alazar_ctrl.channels[2,4,6].data).

Changes proposed in this pull request:
- Add functionality for channellist __getitem__ to allow for a tuple in addition to int and slice.

@jenshnielsen

### CODE REVIEW

**Comment by jenshnielsen** [comment]
@ThorvaldLarsen Sounds reasonable, I think this needs  a test or two. Do you have time to write that or should I do it? \

**Comment by ThorvaldLarsen** [comment]
I have never written tests or looked into how it is done so would be great if you can do that part.

**Comment by jenshnielsen** [comment]
No problem.

@spauka I think this is originally your code. Do you have any comments?

**Comment by jenshnielsen** [comment]
@ThorvaldLarsen I have written some tests.
I guess you know that [2,4,6] can be written as [2:7:2] :) but in general that is not always possible so this is still reasonable

**Comment by ThorvaldLarsen** [comment]
Wasn't actually aware of that. Have never really become friends with slices...
Thanks for the tip.

**Comment by spauka** [comment]
Hey, this makes sense, looks good to me :)

**Pull request merged**
