### PR TITLE
Spyder exclude qcodes from umr

### PR DESCRIPTION
**Pull request by jenshnielsen**
@Dominik-Vogel closes https://github.com/QCoDeS/Qcodes/issues/1008

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Used the solution in https://stackoverflow.com/questions/17728395/detect-where-python-code-is-running-e-g-in-spyder-interpreter-vs-idle-vs-cm to detect spyder not great but should be better

**Comment by WilliamHPNielsen** [comment]
Why is this solution "not great"? Because other environment variables might be called 'SPYDER_lalala'?

**Comment by jenshnielsen** [comment]
Yes or SPYDER may stop using the env variable name. Spyder basically uses env variables for lightweight Inter process communication between the gui and the ipython kernel

**Comment by jenshnielsen** [comment]
If i am a good open source citizen I should really submit a patch to Spyder to add an api for this

**Comment by WilliamHPNielsen** [comment]
I see, thanks for explaining that. I don't think anyone would mind you being a good citizen.

But I guess this solution is OK for now.

**Comment by jenshnielsen** [comment]
This does not seem to be an issue but rather that stuff that has not actually been imported will be marked as reloaded for some reason

**Pull request merged**
