### PR TITLE
raise warning level for parameters that cannot be updated

### PR DESCRIPTION
**Pull request by jenshnielsen**
This makes it easier to spot issues such as #1010 (and another one that I will push a fix for shortly)

### CODE REVIEW

**Comment by jenshnielsen** [comment]
This would also have worked for #1013

**Comment by jenshnielsen** [comment]
I was convinced it was this ◀️  idiot but anyway

**Comment by jenshnielsen** [comment]
I think it is correct to catch all because we don't want to stop qcodes due to any failed snapshot update but we may want to handle different exceptions in a different way

**Comment by jenshnielsen** [comment]
@WilliamHPNielsen Changed it a bit to add the exception info to the file based logger

**Comment by jenshnielsen** [comment]
@WilliamHPNielsen as requested

**Comment by WilliamHPNielsen** [comment]
Looks good.

**Pull request merged**
