### PR TITLE
Add example notebook for R&S SGS100A RF source

### PR DESCRIPTION
**Pull request by mgunyho**
Hi,

There was no example notebook for R&S SGS100A, so I created a very simple one. It's basically just `print_readable_snapshot()` and then setting a power and a frequency, and enabling/disabling RF output. The driver has a lot of parameters that I didn't test, but they can be added later. I tested this with a real device.

### CODE REVIEW

**Review by astafan8 — APPROVED** [review]
That's great, thank you!

**Comment by astafan8** [comment]
@mgunyho could you disable the autmatic execution of the notebook as described here https://qcodes.github.io/Qcodes/examples/writing_drivers/Creating-Instrument-Drivers.html#Documentation ? and then we'll merge

**Comment by mgunyho** [comment]
Ah, I forgot about that. Fixed now. Sorry about the delay.

**Comment by jenshnielsen** [comment]
Bors merge

**Comment by jenshnielsen** [comment]
bors merge

**Pull request merged**
