### PR TITLE
added config needed for wrappers to main qcodes

### PR DESCRIPTION
**Pull request by Dominik-Vogel**
I think we should generally have all the available options in the main qcodes config whether they are needed or not to avoid a copy pasting of files upon every install. Alternatively we should make better error messages.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
I don't really like having unused config objects. At the least the doc string should clarify that it's not used inside qcodes

**Comment by Dominik-Vogel** [comment]
Good point to add a comment!

**Comment by Dominik-Vogel** [comment]
Unfortunately there seems to be no good way to add comments to json files...

**Comment by jenshnielsen** [comment]
No but you can add it to the description in the schema

**Pull request merged**
