### PR TITLE
Add ability to get parameter after set to dond

### PR DESCRIPTION
**Pull request by jenshnielsen**
For some instruments it may be a good idea to get the value after setting it and store that in the dataset rather than relying on the instrument being able to set the exact value. 

This implements that by extending the Sweeps classes with a boolean. This could be extended to read a flag from the parameter giving the parameter a trait to indicate if it has been set

This is also a small step towards fixing #4695 since it will become possible to get the value of a parameter that one sets

To make this easier to demonstrate ManualParameters have been improved to log using the instrument logger

TODO 
- [x] Documentation (examples + docstrings)
- [x] Tests
- [x] release notes

### CODE REVIEW

**Review by astafan8 — COMMENTED** [review]
very very nice idea! and also quite a small change as enabled by the earlier refactor :)

**Comment by jenshnielsen** [comment]
@astafan8 ready for review

**Review by astafan8 — APPROVED** [review]
looks great :)

**Comment by jenshnielsen** [comment]
bors merge

**Comment by jenshnielsen** [comment]
bors merge

**Comment by jenshnielsen** [comment]
bors merge

**Comment by jenshnielsen** [comment]
bors cancel

**Pull request merged**
