### PR TITLE
Fixed #4080 resizing of hdf5 array

### LINKED ISSUE #4080: HDF5 error with 'slow' acquisition of 2D array
## Steps to reproduce:
import qcodes as qc

from qcodes.data import hdf5_format
from qcodes.data.data_set import DataSet

from qcodes.tests.instrument_mocks import MockParabola

DataSet.default_formatter = hdf5_format.HDF5Format()

mockParabola = MockParabola(name='MockParabola')

loop = qc.Loop(mockParabola.x[-100:100:1], delay=0.1).loop(
    mockParabola.y[-100:100:1]).each(mockParabola.x)
loop.run(name='test_hdf5')

## Exception:

  File "c:\projects\sldesnoo.qcodes\qcodes\data\hdf5_format.py", line 243, in write
    new_data_shape)

ValueError: cannot reshape array of size 40000 into shape (7801,1)

## Proposed fix:

Added .flat on line 243:
            dset[old_dlen:new_dlen] = x.flat[old_dlen:new_dlen].reshape(
                new_data_shape)

### PR DESCRIPTION
**Pull request by sldesnoo-Delft**
Use flat array when selecting the new data for hdf5 array update to write to file.

Closes #4080

### CODE REVIEW

**Review by astafan8 — APPROVED** [review]
Thanks! would you be willing to add a test for this? could probably be just the code from the issue.

**Comment by astafan8** [comment]
@sldesnoo-Delft would you be willing to add a test for this? could probably be just the code from the issue.

and could you also add a newsfragment (see here https://qcodes.github.io/Qcodes/community/contributing.html#pull-requests ) ?

**Comment by sldesnoo-Delft** [comment]
> @sldesnoo-Delft would you be willing to add a test for this? could probably be just the code from the issue.
> 
> and could you also add a newsfragment (see here https://qcodes.github.io/Qcodes/community/contributing.html#pull-requests ) ?

@astafan8, I definitely would like to do so. Unfortunately I'm very busy at the moment. Can I do so in a few weeks?

**Comment by astafan8** [comment]
@sldesnoo-Delft sure, no problem! perhaps you'll have time before ~mid May when we plan to make the next release?

**Comment by jenshnielsen** [comment]
bors merge

**Pull request merged**
