### PR TITLE
driver / RUDAT 13G 90 

### PR DESCRIPTION
**Pull request by sohailc**
Added a driver for the microcircuits RUDAT 13G 90 attenutator

### CODE REVIEW

**Comment by Dominik-Vogel** [comment]
Looking at it again I think you should build on the old PR. You can simply push to that branch.

**Comment by sohailc** [comment]
Actually, @Dominik-Vogel , I think I should keep the new PR. Your PR (#813) adds a driver for the rcdat_6000_60, which I do not have. I would either have to remove your driver or I'd have to push untested code, neither of which is desirable. I think we should merge this PR (once it is approved) and than in your branch you can use my mixin class.

**Comment by sohailc** [comment]
Using a Mixin class did not work well with mypy. A similar situation is described here: 
https://github.com/python/mypy/issues/4001

I think the only solution is to make a subclass USBHIDInstrument and inherit from that.

**Comment by Dominik-Vogel** [comment]
Dear @sohailc, I would prefer making a mixin and make an exception for mypy until the issue gets resolved. The reason for this is, that mypy is checking, a commodity feature, and the mixin is required to not repeat the same code: For minicircuits there exist quite a few devices that are ethernet and usb connectable. If you want to make a consistent driver you can implement all the same commands and then only add a mixin for the usb case.

**Comment by sohailc** [comment]
Ok, I am using a Mixin, have another look, @Dominik-Vogel

**Pull request merged**
