### PR TITLE
add report and images for benchmark of awg5208

### PR DESCRIPTION
**Pull request by mltls**
Changes proposed in this pull request:
- add script for setting up awg
- add script for getting waveforms from oscilloscope
- add script for analysing the data

@WilliamHPNielsen

### CODE REVIEW

**Comment by astafan8** [comment]
Nice! Does this belong to QCoDeS repository though?

**Comment by jenshnielsen** [comment]
I was thinking the same thing. We should think about a good place for this kind of meta documentation about the drivers and performance. Benchmarking scripts may belong if they can be used for some kind of continuous /semi automated benchmarking but the report probably does not

**Comment by astafan8** [comment]
@jenshnielsen what about redirecting this PR to StationQ?

**Comment by WilliamHPNielsen** [comment]
Closing this in favour of QCoDeS/Reports#2

**Pull request closed without merging**
