### PR TITLE
Add functions to read and write registers on Alazar and Trigger holdoff for 9360

### PR DESCRIPTION
**Pull request by jenshnielsen**
This is work in progress since it should probably not be merged before its used for anything

### CODE REVIEW

**Comment by jenshnielsen** [comment]
This now has support for enabling and disabling trigger holdoff on the 3260 card. The following 
code illustrates the problem. Triggering at ~200 KHz on a 20 MHz sine signal from a function generator with a trigger pulse per cycle. 


```
import qcodes as qc
from qdev_wrappers.alazar_controllers.ATSChannelController import ATSChannelController
from qdev_wrappers.alazar_controllers.alazar_channel import AlazarChannel
from qcodes.instrument_drivers.AlazarTech.ATS9360 import AlazarTech_ATS9360


alazar = AlazarTech_ATS9360('Alazar')
myctrl = ATSChannelController(name='my_controller', alazar_name='Alazar')
# Configure all settings in the Alazar card
with alazar.syncing():    
    alazar.clock_source('INTERNAL_CLOCK')
    alazar.sample_rate(1_000_000_000)
    alazar.clock_edge('CLOCK_EDGE_RISING')
    alazar.decimation(1)
    alazar.coupling1('DC')
    alazar.coupling2('DC')
    alazar.channel_range1(.4)
    alazar.channel_range2(.4)
    alazar.impedance1(50)
    alazar.impedance2(50)
    alazar.trigger_operation('TRIG_ENGINE_OP_J')
    alazar.trigger_engine1('TRIG_ENGINE_J')
    alazar.trigger_source1('EXTERNAL')
    alazar.trigger_slope1('TRIG_SLOPE_POSITIVE')
    alazar.trigger_level1(160)
    alazar.trigger_engine2('TRIG_ENGINE_K')
    alazar.trigger_source2('DISABLE')
    alazar.trigger_slope2('TRIG_SLOPE_POSITIVE')
    alazar.trigger_level2(128)
    alazar.external_trigger_coupling('DC')
    alazar.external_trigger_range('ETR_2V5')
    alazar.trigger_delay(0)
    alazar.timeout_ticks(0)
    alazar.aux_io_mode('AUX_IN_AUXILIARY') # AUX_IN_TRIGGER_ENABLE for seq mode on
    alazar.aux_io_param('NONE') # TRIG_SLOPE_POSITIVE for seq mode on
    
# Create the acquisition controller which will take care of the data handling and tell it which 
# alazar instrument to talk to. Explicitly pass the default options to the Alazar.
# Dont integrate over samples but avarage over records
myctrl.int_delay(2e-7)
myctrl.int_time(2e-6)
print(myctrl.samples_per_record())

chan4 = AlazarChannel(myctrl, 'myrecvssamples', demod=False, average_records=False, integrate_samples=False)
myctrl.channels.append(chan4)

alazar.trigger_holdoff(False)
chan4.num_averages(1)
chan4.records_per_buffer(10)
chan4.alazar_channel('A')
chan4.prepare_channel()
# Measure this 
data4 = qc.Measure(chan4.data).run()
qc.MatPlot(data4.my_controller_myrecvssamples_data)

alazar.trigger_holdoff(True)
chan4.num_averages(1)
chan4.records_per_buffer(10)
chan4.alazar_channel('A')
chan4.prepare_channel()
# Measure this 
data4 = qc.Measure(chan4.data).run()
qc.MatPlot(data4.my_controller_myrecvssamples_data)
```

Produces

**Comment by jenshnielsen** [comment]
Without trigger holdoff
without_trigger_holdoff

With trigger holdoff
with_trigger_holdoff

**Comment by astafan8** [comment]
@jenshnielsen thanks for looking into it! Perhaps, this information can be copy-pasted and pushed to the `Reports` repo?

**Comment by jenshnielsen** [comment]
@QCoDeS/core I think this is ready for review the report is up at https://github.com/QCoDeS/Reports/pull/7

The firmware needed has been released officially yesterday

**Pull request merged**
