### PR TITLE
Update: zhinst instrument driver stubs

### PR DESCRIPTION
**Pull request by tobiasah**
Update driver stubs for Zurich Instruments devices.

With the latest release of LabOne 22.02 the QCoDeS driver for our instruments changed quite a bit. Not only did we add 
support for all of our devices but also we changed the import statements. 

This PR maps the existing stubs to the correct imports and adds new files for the newly supported device.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
@tobiasah Thanks ;) I can see that you closed https://github.com/zhinst/zhinst-qcodes/issues/4 
If I remember correctly that was the last remaining usecase for the old QCoDeS driver so perhaps we should remove that one soon too

**Comment by jenshnielsen** [comment]
Should we update setup.cfg to ensuer that we depend on the 0.3 series of zhinst-qcodes?

**Comment by tobiasah** [comment]
I updated the setup.cfg 
Thanks for the hint

**Comment by jenshnielsen** [comment]
@tobiasah I pushed a pr with a few small tweaks here https://github.com/tobiasah/Qcodes/pull/1 which should merge into this branch/pr before we merge it

**Review by jenshnielsen — APPROVED** [review]
bors merge

**Comment by jenshnielsen** [comment]
bors merge

**Pull request merged**
