### PR TITLE
Fix: QDac save_val when not ramping voltage

### PR DESCRIPTION
**Pull request by WilliamHPNielsen**
The QDac was not saving UNramping voltages

@jenshnielsen

### CODE REVIEW

**Comment by jenshnielsen** [comment]
This should not be needed as std paramers already call _save_val as they are calling the set and get cmds

**Comment by WilliamHPNielsen** [comment]
I believe you are right. I'll take my head out of my ass and look at this again.

**Comment by WilliamHPNielsen** [comment]
Now it's the other way round 😄

**Comment by giulioungaretti** [comment]
@WilliamHPNielsen so this PR is actually fixing a double call to save_val ?

**Comment by WilliamHPNielsen** [comment]
@giulioungaretti Correct. You have to appreciate the irony.

**Comment by jenshnielsen** [comment]
I think this can be merged?

**Comment by WilliamHPNielsen** [comment]
@jenshnielsen Do you want to give a positive review, or should I force merge?

**Comment by jenshnielsen** [comment]
done

**Pull request merged**
