### PR TITLE
fix for hdf5 formatter metadata

### LINKED ISSUE #442: hdf5 formatter crashed for simple dataset
A minimal example:
```
import qcodes
import qcodes.tests.data_mocks
from qcodes.data.hdf5_format import HDF5Format
qcodes.DataSet.default_formatter = HDF5Format()

alldata=qcodes.tests.data_mocks.DataSet2D()
    
alldata.metadata={'a': ['hi', 'there'] }
alldata.write(write_metadata=True)
```

### PR DESCRIPTION
**Pull request by peendebak**
Fixes #442 

@unga @AdriaanRol @core

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Can we change the example in #442 into a simple test for this?

**Comment by peendebak** [comment]
@jenshnielsen Feel free to add the test, it should be a simple copy and past of #442.

**Comment by giulioungaretti** [comment]
@peendebak  can I ask for an explanation of the crash and the fix ? It's not clear from the issue what's broken, and the same from the change  :D

**Comment by peendebak** [comment]
A list is converted to an array of shape (k, ). This cannot be assigned to the hdf structure which is of shape (1,k). So we reshape the data so it can fit @unga

**Comment by jenshnielsen** [comment]
Looks good to me

**Pull request merged**
