### PR TITLE
Docs: RST syntax fixes 

### PR DESCRIPTION
**Pull request by jenshnielsen**
Just a few fixes to the rst syntax in the documentation

### CODE REVIEW

**Comment by giulioungaretti** [comment]
<3

**Comment by jenshnielsen** [comment]
This should drop the number of Sphinx warnings from 227 to 132

**Comment by peendebak** [comment]
@jenshnielsen Could you see whether #406 can be pulled into this PR as well? It fixes the automatically generated docstrings.

**Comment by jenshnielsen** [comment]
@peendebak Yes that change looks save. I have cherry-picked the relevant commit onto this branch

**Comment by jenshnielsen** [comment]
Merged by approval of @giulioungaretti

**Pull request merged**
