### PR TITLE
Instr param

### PR DESCRIPTION
**Pull request by AdriaanRol**
Changes proposed in this pull request:
- Adds new InstrumentParameter class 
- Adds test for the class 
- Instrument parameter is very useful for "meta-instruments" or other instruments that require references to other instruments. This is a feature we use a lot in our lab. 

@giulioungaretti

### CODE REVIEW

**Comment by AdriaanRol** [comment]
@jenshnielsen, good suggestions, I'll make the changes.

**Comment by AdriaanRol** [comment]
@jenshnielsen , I addressed your comments, let me know what you think.

**Comment by jenshnielsen** [comment]
looks good to me, will just wait a bit and see if anyone else have something to add

**Comment by WilliamHPNielsen** [comment]
No objections.

**Pull request merged**
