### PR TITLE
driver/Rigol DS4000 series oscilloscopes

### PR DESCRIPTION
**Pull request by YakBizzarro**
Based on the driver in PR #738 
It add readout in ArrayParameter (code borrowed from TPS2012), read of internal memory (raw mode) and bunch of functions. It uses binary format readout to improve speed compared to plain ASCII.
To work properly, it requires PR #752 merged.

@sohailc @WilliamHPNielsen

### CODE REVIEW

**Comment by jenshnielsen** [comment]
@YakBizzarro #752 is merged

**Comment by YakBizzarro** [comment]
@jenshnielsen Thank you!

**Comment by peendebak** [comment]
@YakBizzarro @jenshnielsen The only open issue here is a warning from codacy/pr. It might already have been solved. Could you retrigging the codacy test?

**Comment by jenshnielsen** [comment]
@YakBizzarro Don't worry about that its a false positive due to the way that Deferred_operation works

**Pull request merged**
