### PR TITLE
Don't enforce equal length blob data in add_results

### PR DESCRIPTION
**Pull request by jenshnielsen**
Replaces #1429

### CODE REVIEW

**Comment by jenshnielsen** [comment]
@ThorvaldLarsen @QCoDeS/core This should now pass the existing tests and have it's own test and be ready for review

**Comment by ThorvaldLarsen** [comment]
@jenshnielsen do you want me to test this at T3 before merge?

**Comment by jenshnielsen** [comment]
We realized that this needs some more work as it does not enforce that dependent parameters have equal lenght. I think @WilliamHPNielsen is working on that

**Comment by jenshnielsen** [comment]
This is redundant now

**Pull request closed without merging**
