### PR TITLE
bugfix qtplot png representation

### PR DESCRIPTION
**Pull request by dpfranke**
I haven't looked into the details, but this fixes the png representation on my machine. Probably a change in pyqtgraph?
@jenshnielsen @WilliamHPNielsen

### CODE REVIEW

**Comment by WilliamHPNielsen** [comment]
@dpfranke, two questions: what problem does this PR solve? What versions of packages are you using?

When I play around with
```
PyQt5 (5.9)
pyqtgraph (0.10.0)
QtAwesome (0.4.4)
qtconsole (4.3.1)
QtPy (1.3.1)
```

I get a `UnicodeDecodeError` when using this PR, but a (seemingly) nice bytestring when using the current master version.

**Comment by dpfranke** [comment]
Ok, I get
`AttributeError: 'QByteArray' object has no attribute '_getValue'`
with the master version. This seems to be connected to the remote argument, working / failing example for IPython:
`from qcodes.plots.pyqtgraph import QtPlot`
`plot = QtPlot(remote=False)`
`plot`

**Comment by WilliamHPNielsen** [comment]
@dpfranke, I see, thanks for clarifying. I think the way to go is then indeed as you suggest to only apply the fix from this PR if `remote == False`. That would at least be the quickfix.

**Comment by dpfranke** [comment]
couldn't find that option, now using `hasattr`

Could you check whether that work around works for you, @WilliamHPNielsen

**Comment by astafan8** [comment]
do i understand correctly that this png/plotting functionality is not and **cannot be** automatically tested, hence the complaints about code coverage? If so, then let's merge, because I see that the solution works for both @dpfranke and @WilliamHPNielsen ?

**Comment by dpfranke** [comment]
@WilliamHPNielsen we use it as part of our (qt-based) data viewer / browser

**Pull request merged**
