### PR TITLE
NumpyJSONEncoder: Add support for the uncertanties' UFloat type

### PR DESCRIPTION
**Pull request by Astlaan**
Related to a feature needed by Quantify, a library using QCoDeS:
[https://gitlab.com/quantify-os/quantify-core/-/issues/152](https://gitlab.com/quantify-os/quantify-core/-/issues/152)

Changes proposed in this pull request:
- Extended the NumpyJSONEncoder class in utils/helpers.py, so that it can now also encode numbers with uncertainties (i.e. with the type UFloat defined in the uncertainties package) so that it can be encoded in JSON in a manner similar to how numbers.Complex already is.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
@Astlaan In addition to adding uncertainties to requirements.txt you should also add it to setup.cfg for all the ci jobs to build.

**Comment by Astlaan** [comment]
> @Astlaan In addition to adding uncertainties to requirements.txt you should also add it to setup.cfg for all the ci jobs to build.

Hi! Thanks.
I have added to both files, but still seems to fail to install all the dependencies...

**Comment by jenshnielsen** [comment]
Hi you also need to add the dependencies for conda testing here https://github.com/QCoDeS/Qcodes/blob/master/.github/static/environment_forge_full.yml

**Comment by Astlaan** [comment]
> Hi you also need to add the dependencies for conda testing here https://github.com/QCoDeS/Qcodes/blob/master/.github/static/environment_forge_full.yml

Looks good now.

**Review by jenshnielsen — APPROVED** [review]

**Pull request merged**
