### PR TITLE
Added a failing test for PyQT plotting (passes <0.1.7, fails at later versions). 

### PR DESCRIPTION
**Pull request by AdriaanRol**
Includes a self contained test for #769. 
Includes all the changes from #770. 

@jenshnielsen I did not know how to make this PR clean into your branch as there are many forks. 
Very important note, I have tested that this test passes on the 0.1.7 version of QCoDeS but not on the more recent update. 

```
[Adriaan:...arloLab_Repositories/Qcodes]$ py.test qcodes/tests/test_plots.py -v      (4ee1167)
===================================== test session starts ======================================
platform darwin -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0 -- /Users/Adriaan/anaconda/bin/python
cachedir: .cache
rootdir: /Users/Adriaan/GitHubRepos/DiCarloLab_Repositories/Qcodes, inifile:
plugins: cov-2.4.0
collected 3 items

qcodes/tests/test_plots.py::TestQtPlot::test_creation PASSED
qcodes/tests/test_plots.py::TestQtPlot::test_simple_plot FAILED
qcodes/tests/test_plots.py::TestMatPlot::test_creation PASSED

=========================================== FAILURES ===========================================
_________________________________ TestQtPlot.test_simple_plot __________________________________

self = <qcodes.tests.test_plots.TestQtPlot testMethod=test_simple_plot>

    def test_simple_plot(self):
        plotQ = QtPlot(remote=False, show_window=False, interval=0)
        plotQ.add_subplot()

        main_QtPlot = QtPlot(
            window_title='Main plotmon of TestQtPlot',
            figsize=(600, 400))

        x = np.arange(0, 10e-6, 1e-9)
        f = 2e6
        y = np.cos(2*np.pi*f*x)

        for j in range(4):
            main_QtPlot.add(x=x, y=y,
                            xlabel='Time', xunit='s',
                            ylabel='Amplitude', yunit='V',
                            subplot=j+1,
>                           symbol='o', symbolSize=5)

qcodes/tests/test_plots.py:65:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
qcodes/plots/base.py:91: in add
    self.add_to_plot(**kwargs)
qcodes/plots/pyqtgraph.py:149: in add_to_plot
    self.fixUnitScaling()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <qcodes.plots.pyqtgraph.QtPlot object at 0x112a59b00>, startranges = None

    def fixUnitScaling(self, startranges: Optional[Dict[str, Dict[str, Union[float,int]]]]=None):
        """
            Disable SI rescaling if units are not standard units and limit
            ranges to data if known.

            Args:

                startranges: The plot can automatically infer the full ranges
                             array parameters. However it has no knowledge of the
                             ranges or regular parameters. You can explicitly pass
                             in the values here as a dict of the form
                             {'paramtername': {max: value, min:value}}
            """
        axismapping = {'x': 'bottom',
                       'y': 'left'}
        standardunits = self.standardunits
        for i, plot in enumerate(self.subplots):
            # make a dict mapping axis labels to axis positions
            for axis in ('x', 'y', 'z'):
>               if self.traces[i]['config'].get(axis):
E               ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

qcodes/plots/pyqtgraph.py:529: ValueError
============================== 1 failed, 2 passed in 7.86 seconds ==============================
```

### CODE REVIEW

**Comment by AdriaanRol** [comment]
As a separate additon I've put the Travis.Yaml file we use for PycQED that allows testing pyqtgraph plotting in the online builds (so that we can get rid of the `@skipif` statements). 
```yaml
language: python
notifications:
  email: true

cache: pip

python:
  - "3.6"

env:
    - TRAVISCI=true PYTHON=3.6


before_install:
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/mc
    - export PATH=/home/travis/mc/bin:$PATH


# command to install dependencies
install:
    - export GIT_FULL_HASH=`git rev-parse HEAD`
    - conda update conda --yes
    - conda create -n test_env python=${PYTHON} --yes
    - source activate test_env
    - conda install numpy scipy pyopengl pytest flake8 six coverage matplotlib --yes
    - conda install -c bioconda pygraphviz --yes
    - conda install cython --yes
    - conda install pyqt --yes;

    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install git+git://github.com/DiCarloLab-Delft/Qcodes.git
    - pip install coverage pytest-cov pytest --upgrade
    - pip install codacy-coverage
    - echo ${QT}
    - echo ${TEST}
    - echo ${PYTHON}
    - pip install -e .

before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

# command to run tests
script:
    - py.test pycqed/tests --cov=pycqed --cov-report xml --cov-config=.coveragerc

after_success:
    - pip install codacy-coverage
    - python-codacy-coverage -r coverage.xml

```

**Comment by jenshnielsen** [comment]
@AdriaanRol Thanks I just pushed a fix to get the tests passing locally. Thanks for the Travis script. It's been on my list but I haven't gotten around to do it yet. I will add that as a new PR

**Comment by AdriaanRol** [comment]
@jenshnielsen , I haven't run your updated code but I'm wondering do the correct units get displayed now (as they are clearly not None).

**Comment by jenshnielsen** [comment]
The scaling code will do nothing as as the trace data structure is completely different from the one defined by the loop but it will not crash

**Comment by AdriaanRol** [comment]
@jenshnielsen , I guess I'll have to check it out then. 

It would be to bad though as this is something that previously worked fine (at least for us) and would then be broken upon updating.

**Comment by jenshnielsen** [comment]
I don't think it's broken but the new functionality will just do exactly nothing for you as it cant find the units and labels of your plot it can't update them

**Comment by AdriaanRol** [comment]
@jenshnielsen I guess then my question is, will it find it if I give it as arguments to the plot function as it is in the example test I made? (I would assume it does).

**Pull request merged**
