### PR TITLE
Restore deprecated parameter setters and getters

### PR DESCRIPTION
**Pull request by jenshnielsen**
On top of #788 

Basically add set and get back for delay and step as deprecated functions to unbreak anything that depends on it along with allowing step to be zero as documented in the tutorial.

Also updates the tutorial to use non deprecated properties

### CODE REVIEW

**Comment by jenshnielsen** [comment]
@damazter I think the merge of #600 broke some drivers for you. Can you see if this would fix it for you?

**Comment by damazter** [comment]
I put in on my todo list

**Comment by WilliamHPNielsen** [comment]
This does not solve the issue with the `IVVI` driver.

The issue is the following: a parameter is added using the `add_parameter` method with the kwarg `delay`. An error is raised, `
TypeError: __init__() got an unexpected keyword argument 'delay'`

**Comment by jenshnielsen** [comment]
Ok can you merge #788 and I will try to fix that here too

**Comment by WilliamHPNielsen** [comment]
Done.

**Comment by jenshnielsen** [comment]
Ok I think that should have been taken care of now too

**Comment by WilliamHPNielsen** [comment]
As far as I can see, it solves the issue. 👍

**Pull request merged**
