### PR TITLE
Add basic pre-commit config

### PR DESCRIPTION
**Pull request by basnijholt**
I have added `pre-commit` with a bunch of automatic linter tools
* ~~`pyupgrade` - automatically upgrade to modern Python syntax~~ (maybe in another PR)
* ~~`isort` - sort imports as dictated by PEP8~~ (maybe in another PR)
* ~~`black` - apply a default coding style (**developed by the Python software foundation!**)~~ (maybe in another PR)
* ~~`flake8` - find style, syntax, or logical errors by statically parsing code~~ (maybe in another PR)

I've added the check to the a GitHub Action.

### CODE REVIEW

**Comment by basnijholt** [comment]
@GateBuilder, I've changed the scope of this PR to only add `pyupgrade`.

**Comment by astafan8** [comment]
@basnijholt is it possible to configure pyupgrade so that we don't change ~200 files in one PR? the newline characters and empty lines i guess are fine, but f-strings and other stuff i'd prefer to do in separate PR(s).

**Comment by basnijholt** [comment]
@astafan8, I have changed this PR to only do white space filters now.

**Review by astafan8 — COMMENTED** [review]
i'm a bit unease about fixing whitespace chars in css,js,rst,svg(!) etc (non-py files). or si the tool smart enough? :)

**Comment by basnijholt** [comment]
From the SVG, JS, and CSS it's only adding a new line in the end or removing a trailing white-space of the very last line. This cannot break anything.

The white space fixes In the RST files also shouldn't be any problem.

The only time I have ever seen a trailing whitespace matter is in GNU Make files.

**Review by jenshnielsen — APPROVED** [review]

**Pull request merged**
